### PR TITLE
parseFloat numerical metadata

### PR DESCRIPTION
**Pull request by forresto**
https://github.com/the-grid/the-graph/issues/208

### CODE REVIEW

**Comment by forresto** [comment]
This one is ready. @bergie review?

**Comment by davidmaxwaterman** [comment]
I only just looked at this, but it only seems to be addressing x/y metadata...what about other numeric data like width and height? I'd almost say to try to parse it as a number and if it fails then use a string.

**Comment by bergie** [comment]
@davidmaxwaterman actually `width` and `height` shouldn't be specified at this level at all, see the-grid/the-graph#209

**Comment by davidmaxwaterman** [comment]
hrm, ok, but that makes me wonder what happens when you import the file again...is everything the same as it was before?

**Comment by forresto** [comment]
As it is now, width is always 72 and height is a function of the number of ports (something like `Math.max(72, 8*n)`).

**Comment by davidmaxwaterman** [comment]
ok, fair enough. thanks.

**Pull request merged**
